// 装備 72 個の仕様（Mobile Legends の装備に倣った作り直し。2026-10）。
// 装備 ID・名前・アイコンは tools/portraits/item_icons.json を正本として据え置き、能力値・レシピ・固有パッシブを定義する。
// `node tools/equipment_apply.mjs` が master_runtime.json の equipment と tools/equipment_spec.json（英語文の出典）を更新する。
//
// 参考（Mobile Legends 公式の装備ページ。数値は旧版・機械翻訳の表記のため、この作品の能力値の尺度に合わせて丸めた）:
//   ・トゥルーダメージ: Endless Battle（スキル後の通常攻撃に追加の確定ダメージ）、Raptor Machete（一定間隔の通常攻撃に確定ダメージ）
//   ・貫通: Malefic Roar（物理貫通 %）、Divine Glaive（魔法貫通 %）、Hunter Strike / Arcane Boots / Genius Wand（固定貫通）、
//          Blade of the Heptaseas・Genius Wand（防御・魔防の低下）
// 下の「元ネタ」は設計の出典メモ（アプリ内には出さない）。
//
// 価格 = 素材（from）の価格の合計 + 合成手数料（fee）。T1 は price を直接指定。
// 能力値のキー: attack ability_power hp armor magic_resist move_speed cooldown_reduction_pct（既存）
//   + attack_speed_pct crit_chance_pct crit_damage_pct lifesteal_pct spell_vamp_pct armor_pen_pct armor_pen_flat
//     magic_pen_pct magic_pen_flat hp_regen resource_regen ability_power_pct move_speed_pct out_of_combat_move_pct
//     heal_shield_power_pct monster_damage_pct
// effect = { id, v: [...] }（id は Systems/ItemEffects.swift の ItemEffectKind と一致させる）

export const ITEMS = [
  // ───────────────────────────── Attack ─────────────────────────────
  { id: 'EQ001', cat: 'Attack', tier: 1, price: 350, stats: { attack: 25 },
    pn: '鋭刃', pt: '攻撃力 +25。', pne: 'Sharp Edge', pte: 'Plain attack power.' },
  { id: 'EQ007', cat: 'Attack', tier: 1, price: 330, stats: { attack_speed_pct: 22 },
    pn: '疾き刃', pt: '攻撃速度 +22%。', pne: 'Quick Edge', pte: 'Plain attack speed.' },
  { id: 'EQ013', cat: 'Attack', tier: 1, price: 380, stats: { attack: 10, crit_chance_pct: 12 },
    pn: '会心の欠片', pt: '攻撃力 +10、クリティカル率 +12%。', pne: 'Crit Shard', pte: 'A little attack power and crit chance.' },
  { id: 'EQ019', cat: 'Attack', tier: 2, from: ['EQ007', 'EQ007'], fee: 300,
    stats: { attack_speed_pct: 45, crit_chance_pct: 8, move_speed: 15 },
    effect: { id: 'typhoon', v: [3.5, 100, 3] },
    pn: '疾風連鎖', pt: '3.5 秒ごとに、通常攻撃が対象の周囲の敵 最大 3 体にも 100 の魔法ダメージを与える。',
    pne: 'Gale Chain', pte: 'Every 3.5s, a basic attack also hits up to 3 nearby enemies for 100 magic damage.',
    src: 'Windtalker' },
  { id: 'EQ025', cat: 'Attack', tier: 2, from: ['EQ001', 'EQ003'], fee: 320,
    stats: { attack: 55, hp: 350 },
    effect: { id: 'steamRoller', v: [25, 3] },
    pn: '装甲砕き', pt: 'スキルが命中すると、対象の防御を 3 秒間 25 下げる。',
    pne: 'Armor Breaker', pte: 'Skill hits lower the target\'s armor by 25 for 3s.', src: 'Blade of the Heptaseas' },
  { id: 'EQ031', cat: 'Attack', tier: 2, from: ['EQ001', 'EQ001'], fee: 380,
    stats: { attack: 60, cooldown_reduction_pct: 10, armor_pen_flat: 15 },
    effect: { id: 'hunt', v: [5, 0.3, 2, 15] },
    pn: '追跡の狩り', pt: '物理貫通 +15。同じ敵に通常攻撃を 5 回連続で当てると、2 秒間 移動速度 +30%（CD 15 秒）。',
    pne: 'Relentless Hunt', pte: '+15 physical penetration. 5 consecutive basic attacks on one enemy grant +30% move speed for 2s (15s cooldown).',
    src: 'Hunter Strike' },
  { id: 'EQ037', cat: 'Attack', tier: 2, from: ['EQ007', 'EQ013'], fee: 300,
    stats: { attack: 28, attack_speed_pct: 22, crit_chance_pct: 25 },
    effect: { id: 'frenzy', v: [0.25, 2] },
    pn: '狂乱の連撃', pt: 'クリティカルを出すと、2 秒間 攻撃速度 +25%。',
    pne: 'Frenzied Flurry', pte: 'Critical hits grant +25% attack speed for 2s.', src: 'Scarlet Phantom' },
  { id: 'EQ043', cat: 'Attack', tier: 3, from: ['EQ025', 'EQ031'], fee: 650,
    stats: { attack: 85, hp: 350, cooldown_reduction_pct: 10, lifesteal_pct: 10 },
    effect: { id: 'divineJustice', v: [0.6, 3, 1.5, 80, 0.4] },
    pn: '裁きの一撃', pt: 'スキルを使うと、3 秒以内の次の通常攻撃が 攻撃力の 60% の確定ダメージを追加で与え、80（+攻撃力の 40%）HP を回復する（CD 1.5 秒）。',
    pne: 'Verdict Strike', pte: 'After using a skill, the next basic attack within 3s deals extra true damage equal to 60% attack and heals 80 (+40% attack) HP (1.5s cooldown).',
    src: 'Endless Battle（確定ダメージ）' },
  { id: 'EQ049', cat: 'Attack', tier: 3, from: ['EQ031', 'EQ001', 'EQ001'], fee: 600,
    stats: { attack: 150, move_speed_pct: 5 },
    effect: { id: 'despair', v: [0.5, 0.25] },
    pn: '断罪の刃', pt: 'HP が 50% 以下の敵へ与えるダメージ +25%。',
    pne: 'Executioner\'s Edge', pte: 'Deal +25% damage to enemies at or below 50% HP.', src: 'Blade of Despair' },
  { id: 'EQ055', cat: 'Attack', tier: 3, from: ['EQ037', 'EQ013'], fee: 600,
    stats: { attack: 60, crit_chance_pct: 40, crit_damage_pct: 40 },
    pn: '紅雷の会心', pt: 'クリティカルダメージ +40%。',
    pne: 'Crimson Crit', pte: 'Critical hits deal +40% more damage.', src: 'Berserker\'s Fury' },
  { id: 'EQ061', cat: 'Attack', tier: 3, from: ['EQ031', 'EQ013'], fee: 600,
    stats: { attack: 70, armor_pen_pct: 40 },
    pn: '防御貫通', pt: '物理貫通 +40%（敵の防御を 40% 無視する）。',
    pne: 'Armor Piercer', pte: '+40% physical penetration (ignores 40% of the target\'s armor).', src: 'Malefic Roar（貫通）' },
  { id: 'EQ067', cat: 'Attack', tier: 3, from: ['EQ019', 'EQ001'], fee: 600,
    stats: { attack: 45, attack_speed_pct: 35, crit_chance_pct: 12 },
    effect: { id: 'eradication', v: [0.09, 60] },
    pn: '生命削り', pt: '通常攻撃が、対象の現在 HP の 9% の物理ダメージを追加で与える（モンスターには最大 60）。',
    pne: 'Life Reaver', pte: 'Basic attacks deal extra physical damage equal to 9% of the target\'s current HP (max 60 against monsters).',
    src: 'Demon Hunter Sword' },

  // ───────────────────────────── Magic ─────────────────────────────
  { id: 'EQ002', cat: 'Magic', tier: 1, price: 360, stats: { ability_power: 30 },
    pn: '魔力の芽', pt: '魔力 +30。', pne: 'Spark of Power', pte: 'Plain ability power.' },
  { id: 'EQ008', cat: 'Magic', tier: 1, price: 330, stats: { ability_power: 12, cooldown_reduction_pct: 8, resource_regen: 8 },
    pn: '巡る魔力', pt: '魔力 +12、CD 短縮 +8%、リソース回復 +8。', pne: 'Flowing Mana', pte: 'A little power, cooldown reduction and resource regen.' },
  { id: 'EQ014', cat: 'Magic', tier: 1, price: 370, stats: { ability_power: 12, hp: 250 },
    pn: '生命の魔晶', pt: '魔力 +12、最大 HP +250。', pne: 'Vital Crystal', pte: 'A little power and max HP.' },
  { id: 'EQ020', cat: 'Magic', tier: 2, from: ['EQ002', 'EQ008'], fee: 330,
    stats: { ability_power: 62, move_speed: 12, magic_pen_flat: 12 },
    effect: { id: 'geniusShred', v: [3, 10, 3, 2] },
    pn: '魔防の綻び', pt: '魔法貫通 +12。ダメージを与えた敵の魔防を 2 秒間 下げる（1 回につき 3〜10、レベルで増加、最大 3 回重ねる）。',
    pne: 'Warding Rift', pte: '+12 magic penetration. Damaging an enemy lowers its magic resist for 2s (3-10 per hit by level, up to 3 stacks).',
    src: 'Genius Wand' },
  { id: 'EQ026', cat: 'Magic', tier: 2, from: ['EQ002', 'EQ014'], fee: 330,
    stats: { ability_power: 66, hp: 320, move_speed: 10 },
    effect: { id: 'incineration', v: [3, 0.03, 10] },
    pn: '焼灼', pt: 'スキルが命中した敵を 3 秒間 燃やし、現在 HP の 3%（最低 10）の確定ダメージを与える。',
    pne: 'Scorch', pte: 'Skill hits burn the target for 3s, dealing true damage equal to 3% of its current HP (min 10).',
    src: 'Glowing Wand' },
  { id: 'EQ032', cat: 'Magic', tier: 2, from: ['EQ014', 'EQ008'], fee: 300,
    stats: { ability_power: 58, hp: 150, spell_vamp_pct: 10 },
    effect: { id: 'iceBond', v: [0.15, 3, 2] },
    pn: '氷結の絆', pt: 'スキルが命中した敵を 3 秒間 15% 減速（2 回まで重なる）。',
    pne: 'Frost Bond', pte: 'Skill hits slow the target by 15% for 3s (stacks twice).', src: 'Ice Queen Wand' },
  { id: 'EQ038', cat: 'Magic', tier: 2, from: ['EQ008', 'EQ008'], fee: 300,
    stats: { ability_power: 55, cooldown_reduction_pct: 10, spell_vamp_pct: 8 },
    effect: { id: 'antiHeal', v: [0.5, 3] },
    pn: '癒しの断絶', pt: 'スキルが命中した敵が受ける回復量を 3 秒間 50% 減らす。',
    pne: 'Mending Severance', pte: 'Skill hits cut the target\'s received healing by 50% for 3s.', src: 'Necklace of Durance' },
  { id: 'EQ044', cat: 'Magic', tier: 3, from: ['EQ020', 'EQ002'], fee: 650,
    stats: { ability_power: 85, magic_pen_pct: 40 },
    pn: '魔防貫通', pt: '魔法貫通 +40%（敵の魔防を 40% 無視する）。',
    pne: 'Veil Piercer', pte: '+40% magic penetration (ignores 40% of the target\'s magic resist).', src: 'Divine Glaive（貫通）' },
  { id: 'EQ050', cat: 'Magic', tier: 3, from: ['EQ002', 'EQ002', 'EQ008'], fee: 600,
    stats: { ability_power: 105, ability_power_pct: 25 },
    pn: '真珠の増幅', pt: '魔力 +25%。', pne: 'Pearl Amplifier', pte: '+25% ability power.', src: 'Holy Crystal' },
  { id: 'EQ056', cat: 'Magic', tier: 3, from: ['EQ038', 'EQ008'], fee: 600,
    stats: { ability_power: 75, cooldown_reduction_pct: 12, resource_regen: 20 },
    effect: { id: 'echo', v: [6, 120, 0.5] },
    pn: '残響', pt: '6 秒ごとに、次のスキルの命中が 120（+魔力の 50%）の魔法ダメージを追加で与える。',
    pne: 'Echo', pte: 'Every 6s, the next skill hit deals 120 (+50% power) bonus magic damage.', src: 'Lightning Truncheon' },
  { id: 'EQ062', cat: 'Magic', tier: 3, from: ['EQ014', 'EQ014', 'EQ002'], fee: 600,
    stats: { ability_power: 130, hp: 420 },
    effect: { id: 'bloodWings', v: [1.5] },
    pn: '血翼の共鳴', pt: '魔力 1 につき 最大 HP +1.5。', pne: 'Bloodwing Resonance', pte: '+1.5 max HP per point of ability power.',
    src: 'Blood Wings' },
  { id: 'EQ068', cat: 'Magic', tier: 3, from: ['EQ032', 'EQ014'], fee: 600,
    stats: { ability_power: 70, hp: 650, spell_vamp_pct: 22 },
    effect: { id: 'reload', v: [0.1] },
    pn: '再装填', pt: '敵ヒーローを倒すと、最大 HP の 10% を回復する。',
    pne: 'Reload', pte: 'Killing an enemy hero restores 10% of max HP.', src: 'Concentrated Energy' },

  // ───────────────────────────── Defense ─────────────────────────────
  { id: 'EQ003', cat: 'Defense', tier: 1, price: 400, stats: { hp: 400 },
    pn: '頑健', pt: '最大 HP +400。', pne: 'Sturdy', pte: 'Plain max HP.' },
  { id: 'EQ009', cat: 'Defense', tier: 1, price: 380, stats: { armor: 32 },
    pn: '堅牢', pt: '防御 +32。', pne: 'Bulwark', pte: 'Plain armor.' },
  { id: 'EQ015', cat: 'Defense', tier: 1, price: 380, stats: { magic_resist: 32 },
    pn: '耐魔', pt: '魔防 +32。', pne: 'Spellward', pte: 'Plain magic resist.' },
  { id: 'EQ021', cat: 'Defense', tier: 2, from: ['EQ009', 'EQ009'], fee: 280,
    stats: { armor: 70 },
    effect: { id: 'counter', v: [0.25] },
    pn: '棘の反撃', pt: '通常攻撃を受けると、攻撃者の攻撃力の 25% の物理ダメージを返す。',
    pne: 'Thorn Retort', pte: 'When hit by a basic attack, reflect 25% of the attacker\'s attack as physical damage.', src: 'Blade Armor' },
  { id: 'EQ027', cat: 'Defense', tier: 2, from: ['EQ003', 'EQ015'], fee: 320,
    stats: { hp: 550, magic_resist: 30, cooldown_reduction_pct: 10, hp_regen: 8, heal_shield_power_pct: 25 },
    pn: '神託', pt: '与えるシールド・回復量 +25%、HP 回復が増える。', pne: 'Oracle', pte: '+25% shield and healing power, and extra HP regen.',
    src: 'Oracle' },
  { id: 'EQ033', cat: 'Defense', tier: 2, from: ['EQ003', 'EQ009'], fee: 320,
    stats: { hp: 600, armor: 42, hp_regen: 10 },
    effect: { id: 'intimidation', v: [0.06, 3, 2] },
    pn: '威圧', pt: '敵ヒーローの通常攻撃を受けると、その敵の与ダメージを 2 秒間 6% 下げる（3 回まで重なる）。',
    pne: 'Intimidate', pte: 'Hits from enemy heroes\' basic attacks cut their damage dealt by 6% for 2s (stacks 3 times).',
    src: 'Antique Cuirass' },
  { id: 'EQ039', cat: 'Defense', tier: 2, from: ['EQ003', 'EQ009'], fee: 340,
    stats: { hp: 650, armor: 36, cooldown_reduction_pct: 10 },
    effect: { id: 'thunder', v: [0.02, 0.3, 1.5, 1.5] },
    pn: '雷帯の一撃', pt: '次の通常攻撃が 最大 HP の 2% の追加ダメージを与え、対象を 1.5 秒間 30% 減速する（CD 1.5 秒）。',
    pne: 'Thunderband Strike', pte: 'The next basic attack deals bonus damage equal to 2% of your max HP and slows the target by 30% for 1.5s (1.5s cooldown).',
    src: 'Thunder Belt' },
  { id: 'EQ045', cat: 'Defense', tier: 3, from: ['EQ003', 'EQ015', 'EQ003'], fee: 600,
    stats: { hp: 950, magic_resist: 55 },
    effect: { id: 'cursedAura', v: [8, 0.012, 420, 0.5] },
    pn: '呪いの怨嗟', pt: '周囲 420 の敵に毎秒 8（+対象の最大 HP の 1.2%）の魔法ダメージ。ミニオンへは +50%。',
    pne: 'Curse of Wrath', pte: 'Enemies within 420 take 8 (+1.2% of their max HP) magic damage per second. +50% against minions.',
    src: 'Cursed Helmet' },
  { id: 'EQ051', cat: 'Defense', tier: 3, from: ['EQ027', 'EQ015'], fee: 600,
    stats: { hp: 850, magic_resist: 62, hp_regen: 14 },
    effect: { id: 'athena', v: [30, 300, 45, 1150] },
    pn: '守護の盾', pt: '30 秒ごとにシールドを得る（300 から始まり、試合が進むほど増え、最大 1150）。',
    pne: 'Guardian Shield', pte: 'Gain a shield every 30s (starts at 300, grows as the match goes on, up to 1150).', src: 'Athena\'s Shield' },
  { id: 'EQ057', cat: 'Defense', tier: 3, from: ['EQ003', 'EQ003', 'EQ001'], fee: 600,
    stats: { attack: 18, hp: 950, cooldown_reduction_pct: 10 },
    effect: { id: 'demonization', v: [0.4, 0.5, 0.3, 5, 50] },
    pn: '魔人化', pt: 'HP が 40% を下回ると 5 秒間、被ダメージ −50%、ライフスティール +30%（CD 50 秒）。',
    pne: 'Demonic Surge', pte: 'Below 40% HP, take 50% less damage and gain +30% lifesteal for 5s (50s cooldown).', src: 'Queen\'s Wings' },
  { id: 'EQ063', cat: 'Defense', tier: 3, from: ['EQ003', 'EQ003', 'EQ033'], fee: 500,
    stats: { hp: 1250, hp_regen: 40 },
    effect: { id: 'twilight', v: [900] },
    pn: '黄昏の挑戦', pt: '1 回の物理ダメージで受けるダメージは最大 900 まで。',
    pne: 'Twilight Challenge', pte: 'Physical damage taken from a single hit is capped at 900.', src: 'Twilight Armor' },
  { id: 'EQ069', cat: 'Defense', tier: 3, from: ['EQ009', 'EQ021'], fee: 600,
    stats: { armor: 90, cooldown_reduction_pct: 10, resource_regen: 15 },
    effect: { id: 'dominance', v: [600, 0.3, 0.05] },
    pn: '凍てつく威圧', pt: '周囲 600 の敵ヒーローの攻撃速度 −30%、移動速度 −5%。',
    pne: 'Freezing Dominion', pte: 'Enemy heroes within 600 lose 30% attack speed and 5% move speed.', src: 'Dominance Ice' },

  // ───────────────────────────── Movement ─────────────────────────────
  { id: 'EQ004', cat: 'Movement', tier: 1, price: 350, stats: { move_speed: 40 },
    pn: '軽い足取り', pt: '移動速度 +40。', pne: 'Light Step', pte: 'Plain move speed. Limit one boots item.' },
  { id: 'EQ010', cat: 'Movement', tier: 1, price: 330, stats: { move_speed: 30, attack_speed_pct: 12 },
    pn: '駆ける足', pt: '移動速度 +30、攻撃速度 +12%。', pne: 'Racing Stride', pte: 'Move speed and a little attack speed.' },
  { id: 'EQ016', cat: 'Movement', tier: 1, price: 330, stats: { move_speed: 30, cooldown_reduction_pct: 8 },
    pn: '潮の足', pt: '移動速度 +30、CD 短縮 +8%。', pne: 'Tidal Stride', pte: 'Move speed and a little cooldown reduction.' },
  { id: 'EQ022', cat: 'Movement', tier: 2, from: ['EQ004', 'EQ010'], fee: 250,
    stats: { move_speed: 45, attack_speed_pct: 18 },
    pn: '隼の疾走', pt: '移動速度 +45、攻撃速度 +18%。', pne: 'Falcon Dash', pte: 'Move speed and attack speed.', src: 'Swift Boots' },
  { id: 'EQ028', cat: 'Movement', tier: 2, from: ['EQ004', 'EQ015'], fee: 250,
    stats: { move_speed: 42, magic_resist: 28 },
    pn: '水面の守り', pt: '移動速度 +42、魔防 +28。', pne: 'Waterwalker\'s Ward', pte: 'Move speed and magic resist.', src: 'Tough Boots' },
  { id: 'EQ034', cat: 'Movement', tier: 2, from: ['EQ004', 'EQ016'], fee: 250,
    stats: { move_speed: 42, cooldown_reduction_pct: 12 },
    pn: '雲の加速', pt: '移動速度 +42、CD 短縮 +12%。', pne: 'Cloud Haste', pte: 'Move speed and cooldown reduction.', src: 'Magic Shoes' },
  { id: 'EQ040', cat: 'Movement', tier: 2, from: ['EQ004', 'EQ009'], fee: 250,
    stats: { move_speed: 42, armor: 28 },
    pn: '韋駄天の鎧脚', pt: '移動速度 +42、防御 +28。', pne: 'Fleetfoot Plating', pte: 'Move speed and armor.', src: 'Warrior Boots' },
  { id: 'EQ046', cat: 'Movement', tier: 3, from: ['EQ022', 'EQ004'], fee: 450,
    stats: { move_speed: 45, attack_speed_pct: 10, out_of_combat_move_pct: 17 },
    pn: '天翔ける翼', pt: '非戦闘時の移動速度 +17%。', pne: 'Skyward Wings', pte: '+17% move speed while out of combat.', src: 'Rapid Boots' },
  { id: 'EQ052', cat: 'Movement', tier: 3, from: ['EQ034', 'EQ002'], fee: 450,
    stats: { move_speed: 45, magic_pen_flat: 15, cooldown_reduction_pct: 8 },
    pn: '魔の踏破', pt: '魔法貫通 +15。', pne: 'Stormcrosser\'s Pierce', pte: '+15 magic penetration.', src: 'Arcane Boots' },
  { id: 'EQ058', cat: 'Movement', tier: 3, from: ['EQ034', 'EQ014'], fee: 450,
    stats: { move_speed: 42, resource_regen: 30, hp: 200 },
    effect: { id: 'demonShoes', v: [0.1] },
    pn: '魔性の恩恵', pt: '敵ヒーローを倒す・アシストすると、最大 HP の 10% を回復する。',
    pne: 'Fiend\'s Boon', pte: 'Killing or assisting on an enemy hero restores 10% of max HP.', src: 'Demon Shoes' },
  { id: 'EQ064', cat: 'Movement', tier: 3, from: ['EQ022', 'EQ001'], fee: 450,
    stats: { move_speed: 45, attack: 15, armor_pen_flat: 15 },
    pn: '風神の貫き', pt: '物理貫通 +15。', pne: 'Windlord\'s Pierce', pte: '+15 physical penetration.', src: '（Arcane Boots の物理版）' },
  { id: 'EQ070', cat: 'Movement', tier: 3, from: ['EQ040', 'EQ004'], fee: 450,
    stats: { move_speed: 55, armor: 22, magic_resist: 22 },
    pn: '神速の守り', pt: '移動速度 +55、防御・魔防 +22。', pne: 'Pegasus Guard', pte: 'High move speed with armor and magic resist.' },

  // ───────────────────────────── Utility ─────────────────────────────
  { id: 'EQ005', cat: 'Utility', tier: 1, price: 340, stats: { hp: 300, hp_regen: 6 },
    pn: '炉火の加護', pt: '最大 HP +300、HP 回復 +6。', pne: 'Hearth Blessing', pte: 'Max HP and a little HP regen.' },
  { id: 'EQ011', cat: 'Utility', tier: 1, price: 330, stats: { cooldown_reduction_pct: 10, resource_regen: 12 },
    pn: '霊樹の滴', pt: 'CD 短縮 +10%、リソース回復 +12。', pne: 'Spiritwood Dew', pte: 'Cooldown reduction and resource regen.' },
  { id: 'EQ017', cat: 'Utility', tier: 1, price: 350, stats: { attack: 10, lifesteal_pct: 6 },
    pn: '琥珀の渇き', pt: '攻撃力 +10、ライフスティール +6%。', pne: 'Amber Thirst', pte: 'A little attack power and lifesteal.' },
  { id: 'EQ023', cat: 'Utility', tier: 2, from: ['EQ005', 'EQ011'], fee: 280,
    stats: { hp: 300, cooldown_reduction_pct: 18, resource_regen: 20 },
    pn: '霊樹の湧水', pt: 'CD 短縮 +18%、リソース回復 +20、最大 HP +300。', pne: 'Spiritwood Spring', pte: 'Cooldown reduction, resource regen and max HP.',
    src: 'Enchanted Talisman' },
  { id: 'EQ029', cat: 'Utility', tier: 2, from: ['EQ017', 'EQ001'], fee: 300,
    stats: { attack: 45, cooldown_reduction_pct: 8, spell_vamp_pct: 18 },
    pn: '血の渇き', pt: '攻撃力 +45、CD 短縮 +8%、スペルヴァンプ +18%。', pne: 'Bloodthirst', pte: 'Attack power, cooldown reduction and spell vamp.',
    src: 'Bloodlust Axe' },
  { id: 'EQ035', cat: 'Utility', tier: 2, from: ['EQ017', 'EQ015'], fee: 320,
    stats: { attack: 35, magic_resist: 30, lifesteal_pct: 6 },
    effect: { id: 'lifeLine', v: [0.3, 360, 0.08, 3, 40] },
    pn: '命綱', pt: 'HP が 30% を下回ると 3 秒間、360（+最大 HP の 8%）のシールドを得る（CD 40 秒）。',
    pne: 'Lifeline', pte: 'Below 30% HP, gain a shield of 360 (+8% max HP) for 3s (40s cooldown).', src: 'Rose Gold Meteor' },
  { id: 'EQ041', cat: 'Utility', tier: 2, from: ['EQ017', 'EQ001'], fee: 330,
    stats: { attack: 60, lifesteal_pct: 16 },
    effect: { id: 'enthusiasm', v: [0.4, 0.1] },
    pn: '高揚', pt: 'HP が 40% 以下だと、ライフスティール +10%。', pne: 'Zeal', pte: '+10% extra lifesteal while at or below 40% HP.',
    src: 'Haas\'s Claws' },
  { id: 'EQ047', cat: 'Utility', tier: 3, from: ['EQ023', 'EQ002'], fee: 600,
    stats: { ability_power: 65, cooldown_reduction_pct: 15, hp: 200 },
    effect: { id: 'timeCurrent', v: [0.35] },
    pn: '時の潮流', pt: '敵ヒーローを倒す・アシストすると、必殺技のクールダウンを 35% 短縮する。',
    pne: 'Tide of Time', pte: 'Killing or assisting on an enemy hero cuts the ultimate\'s remaining cooldown by 35%.', src: 'Fleeting Time' },
  { id: 'EQ053', cat: 'Utility', tier: 3, from: ['EQ003', 'EQ015', 'EQ005'], fee: 600,
    stats: { hp: 850, magic_resist: 38, hp_regen: 12 },
    effect: { id: 'immortal', v: [0.15, 300, 3, 180] },
    pn: '不死の祝福', pt: '倒れる攻撃を受けても 1 度だけ、最大 HP の 15% で踏みとどまり 3 秒間 300 のシールドを得る（CD 180 秒）。',
    pne: 'Undying Blessing', pte: 'Once, a lethal hit leaves you at 15% max HP with a 300 shield for 3s (180s cooldown).', src: 'Immortality' },
  { id: 'EQ059', cat: 'Utility', tier: 3, from: ['EQ011', 'EQ005', 'EQ003'], fee: 600,
    stats: { hp: 1400, hp_regen: 80 },
    pn: '森の再生', pt: 'HP 回復 +80（最大 HP +1400）。', pne: 'Forest Regeneration', pte: 'Big max HP and strong HP regen.', src: 'Guardian Helmet' },
  { id: 'EQ065', cat: 'Utility', tier: 3, from: ['EQ017', 'EQ007'], fee: 600,
    stats: { attack: 15, attack_speed_pct: 28, lifesteal_pct: 14 },
    pn: '太陽の鼓動', pt: '攻撃速度 +28%、ライフスティール +14%。', pne: 'Solar Pulse', pte: 'Attack speed and strong lifesteal.', src: 'Wind of Nature' },
  { id: 'EQ071', cat: 'Utility', tier: 3, from: ['EQ005', 'EQ011', 'EQ017'], fee: 600,
    stats: { hp: 650, hp_regen: 22, heal_shield_power_pct: 25, cooldown_reduction_pct: 15 },
    pn: '霊花の癒し', pt: '与えるシールド・回復量 +25%、CD 短縮 +15%。', pne: 'Blossom Mending', pte: '+25% shield and healing power with cooldown reduction.' },

  // ───────────────────────────── Jungle（狩猟印が必要・1 個まで） ─────────────────────────────
  { id: 'EQ006', cat: 'Jungle', tier: 1, price: 340, stats: { attack: 18, monster_damage_pct: 25 },
    pn: '狩人の矢', pt: '攻撃力 +18、モンスターへのダメージ +25%。', pne: 'Hunter\'s Arrow', pte: 'Attack power and bonus damage to monsters. Requires Hunter\'s Mark.' },
  { id: 'EQ012', cat: 'Jungle', tier: 1, price: 340, stats: { hp: 150, armor: 15, magic_resist: 15, monster_damage_pct: 20 },
    pn: '番兵の盾', pt: '最大 HP +150、防御・魔防 +15、モンスターへのダメージ +20%。', pne: 'Sentinel\'s Shield', pte: 'Durability and bonus damage to monsters. Requires Hunter\'s Mark.' },
  { id: 'EQ018', cat: 'Jungle', tier: 1, price: 340, stats: { ability_power: 22, monster_damage_pct: 25 },
    pn: '星鉄の矢', pt: '魔力 +22、モンスターへのダメージ +25%。', pne: 'Starsteel Arrow', pte: 'Power and bonus damage to monsters. Requires Hunter\'s Mark.' },
  { id: 'EQ024', cat: 'Jungle', tier: 2, from: ['EQ006', 'EQ001'], fee: 300,
    stats: { attack: 45, armor_pen_pct: 8, monster_damage_pct: 30 },
    pn: '鋭い狩り', pt: '攻撃力 +45、物理貫通 +8%、モンスターへのダメージ +30%。', pne: 'Keen Hunt', pte: 'Attack, +8% physical penetration, bonus damage to monsters. Requires Hunter\'s Mark.' },
  { id: 'EQ030', cat: 'Jungle', tier: 2, from: ['EQ012', 'EQ003'], fee: 280,
    stats: { hp: 400, armor: 22, magic_resist: 22, monster_damage_pct: 25 },
    pn: '堅い狩り', pt: '最大 HP +400、防御・魔防 +22、モンスターへのダメージ +25%。', pne: 'Stout Hunt', pte: 'Durability and bonus damage to monsters. Requires Hunter\'s Mark.' },
  { id: 'EQ036', cat: 'Jungle', tier: 2, from: ['EQ012', 'EQ009'], fee: 280,
    stats: { hp: 250, armor: 45, magic_resist: 18, monster_damage_pct: 25 },
    pn: '鎧の狩り', pt: '最大 HP +250、防御 +45、魔防 +18、モンスターへのダメージ +25%。', pne: 'Armored Hunt', pte: 'Armor-heavy durability and bonus damage to monsters. Requires Hunter\'s Mark.' },
  { id: 'EQ042', cat: 'Jungle', tier: 2, from: ['EQ018', 'EQ002'], fee: 300,
    stats: { ability_power: 50, spell_vamp_pct: 8, monster_damage_pct: 30 },
    pn: '星の狩り', pt: '魔力 +50、スペルヴァンプ +8%、モンスターへのダメージ +30%。', pne: 'Star Hunt', pte: 'Power, spell vamp and bonus damage to monsters. Requires Hunter\'s Mark.' },
  { id: 'EQ048', cat: 'Jungle', tier: 3, from: ['EQ036', 'EQ012'], fee: 600,
    stats: { hp: 700, armor: 60, magic_resist: 40, monster_damage_pct: 20 },
    effect: { id: 'impulse', v: [0.1, 100, 350, 0.3] },
    pn: '衝動', pt: '1 回の攻撃で最大 HP の 10% 以上のダメージを受けると、周囲 350 の敵に 100 の魔法ダメージを与え 30% 減速する。',
    pne: 'Impulse', pte: 'Taking a hit of 10% max HP or more deals 100 magic damage to enemies within 350 and slows them by 30%. Requires Hunter\'s Mark.',
    src: 'Beast Killer' },
  { id: 'EQ054', cat: 'Jungle', tier: 3, from: ['EQ024', 'EQ006'], fee: 600,
    stats: { attack: 70, armor_pen_pct: 15, monster_damage_pct: 40 },
    effect: { id: 'breakout', v: [10, 50, 1.5, 0.3, 1] },
    pn: '急襲の牙', pt: '物理貫通 +15%。10 秒ごとに、次の通常攻撃が最低 50（レベルで増加）の確定ダメージを与え、1 秒間 30% 減速する。',
    pne: 'Ambush Fang', pte: '+15% physical penetration. Every 10s, the next basic attack deals at least 50 true damage (grows with level) and slows by 30% for 1s. Requires Hunter\'s Mark.',
    src: 'Raptor Machete（確定ダメージ・貫通）' },
  { id: 'EQ060', cat: 'Jungle', tier: 3, from: ['EQ042', 'EQ018'], fee: 600,
    stats: { ability_power: 75, spell_vamp_pct: 15, monster_damage_pct: 40 },
    effect: { id: 'reload', v: [0.1] },
    pn: '再装填', pt: '敵ヒーローを倒すと、最大 HP の 10% を回復する。', pne: 'Reload', pte: 'Killing an enemy hero restores 10% of max HP. Requires Hunter\'s Mark.',
    src: 'Star Shard' },
  { id: 'EQ066', cat: 'Jungle', tier: 3, from: ['EQ024', 'EQ018'], fee: 600,
    stats: { attack: 50, ability_power: 45, monster_damage_pct: 35 },
    pn: '彗星の狩り', pt: '攻撃力 +50、魔力 +45、モンスターへのダメージ +35%。', pne: 'Comet Hunt', pte: 'A hybrid of attack and power with bonus damage to monsters. Requires Hunter\'s Mark.' },
  { id: 'EQ072', cat: 'Jungle', tier: 3, from: ['EQ030', 'EQ012'], fee: 600,
    stats: { hp: 900, armor: 40, magic_resist: 40, monster_damage_pct: 30 },
    pn: '塔盾の守り', pt: '最大 HP +900、防御・魔防 +40、モンスターへのダメージ +30%。', pne: 'Towershield Guard', pte: 'Heavy durability with bonus damage to monsters. Requires Hunter\'s Mark.' },
];

/** 価格を求める（T1 は price、T2 以上は 素材の合計 + fee）。 */
export function priced(items = ITEMS) {
  const byId = new Map(items.map((i) => [i.id, i]));
  const price = (id) => {
    const it = byId.get(id);
    if (!it) throw new Error('unknown item ' + id);
    return it.price ?? (it.from.reduce((s, c) => s + price(c), 0) + it.fee);
  };
  return items.map((i) => ({ ...i, price: price(i.id) }));
}
