// 装備の仕様。Mobile Legends: Bang Bang の装備図鑑（日本語クライアント、パッチ 2.2.16 / 2026-09）をそのまま写した総入れ替え（2026-10）。
// 正は、オーナーが提供した実機の図鑑のスクリーンショット（名前・価格・一覧の並び・詳細の能力値と固有パッシブ）。
// 写っていない数値は Mobile Legends Fandom の Module:Equipment/data（2026-09-24 更新）と各パッチノートで補った（src に英語名）。
// `node tools/equipment_apply.mjs` が master_runtime.json の equipment と tools/equipment_spec.json（英語文の出典）を書き出す。
//
// ・ID は図鑑のタブと並び順: 攻撃 EQ1xx、魔法 EQ2xx、防御 EQ3xx、移動 EQ4xx（完成品 → 素材 → ポーションの順）。
//   アプリの一覧は ID 順に並ぶので、図鑑と同じ順になる。複数のタブに出る装備は最初のタブで ID を振り、also に残りのタブを書く。
// ・ジャングル・ロームは装備ではなく、靴に付ける祝福（Systems/GearSystem.swift の GearOption）。
// ・ヒーロー専用の装備（希望のランタン・希望の花・投擲禁止・投擲許可）は入れていない。
// ・単位: 距離は Velstria の単位（MLBB の 1 マス ≒ 100）。時間は秒。
//
// 項目: id, cat（タブ）, tier（3 = 完成品、2 = 素材の合成品、1 = 基本素材）, price（実機の価格）, name / ne（日・英の名前）,
//   tag / tage（一覧の短い説明）, from（素材の ID。同じ素材は個数ぶん並べる）, stats（能力値）, unique（固有の能力値。重ならない）,
//   effects（固有効果 = Systems/ItemEffects.swift の ItemEffectKind と係数 v）, passives（[名前, 文, 英名, 英文]）,
//   consumable（消耗品の効果秒数）, also（ほかに並ぶタブ）, src（MLBB の英語名。メモ）。
// 能力値のキー: STAT_KEYS。混合防御は armor と magic_resist の両方、混合吸血は lifesteal_pct と spell_vamp_pct の両方に書く。

export const CATEGORIES = ['Attack', 'Magic', 'Defense', 'Movement'];

export const STAT_KEYS = [
  'attack', 'ability_power', 'hp', 'armor', 'magic_resist', 'move_speed', 'cooldown_reduction_pct',
  'attack_speed_pct', 'crit_chance_pct', 'crit_damage_pct', 'lifesteal_pct', 'spell_vamp_pct',
  'armor_pen_pct', 'armor_pen_flat', 'magic_pen_pct', 'magic_pen_flat', 'hp_regen', 'resource_regen',
  'ability_power_pct', 'move_speed_pct', 'out_of_combat_move_pct', 'heal_shield_power_pct', 'monster_damage_pct',
  'mana', 'adaptive_attack', 'cc_reduction_pct', 'slow_reduction_pct', 'heal_received_pct',
  'crit_damage_reduction_pct', 'damage_reduction_pct',
];

const ARMOR_BUSTER = ['撃砕', '物理貫通 +30%（「撃砕」を持つ装備どうしは重ならない）。',
  'Armor Buster', '+30% physical penetration (does not stack with other Armor Buster items).'];

export const ITEMS = [
  // ───────────────────────────── 攻撃 ─────────────────────────────
  { id: 'EQ101', cat: 'Attack', tier: 3, price: 2120, name: 'マジックガン', ne: 'Malefic Gun', src: 'Malefic Gun',
    tag: '攻撃範囲増加', tage: 'Attack range', from: ['EQ122', 'EQ132', 'EQ132'],
    stats: { attack: 40, attack_speed_pct: 20, armor_pen_pct: 30 },
    effects: [{ id: 'maleficEnergy', v: [0.12, 0.10, 0.5] }],
    passives: [ARMOR_BUSTER,
      ['マジックエネルギー', '通常攻撃の射程 +12%。通常攻撃が命中すると 0.5 秒間 移動速度 +10%。',
        'Malefic Energy', '+12% basic attack range. Basic attack hits grant +10% move speed for 0.5s.']] },
  { id: 'EQ102', cat: 'Attack', tier: 3, price: 2140, name: '龍神の槍', ne: 'Great Dragon Spear', src: 'Great Dragon Spear',
    tag: 'CD短縮&クリティカル', tage: 'Cooldown & crit', from: ['EQ125', 'EQ129', 'EQ131'],
    stats: { attack: 70, cooldown_reduction_pct: 10, crit_chance_pct: 20 },
    effects: [{ id: 'supremeWarrior', v: [0.30, 7.5, 15] }],
    passives: [['至高の戦士', '必殺技を使うと 7.5 秒間 移動速度 +30%（CD 15 秒）。',
      'Supreme Warrior', 'After casting the ultimate, gain +30% move speed for 7.5s (15s cooldown).']] },
  { id: 'EQ103', cat: 'Attack', tier: 3, price: 2050, name: 'トライデント', ne: 'Sea Halberd', src: 'Sea Halberd',
    tag: '回復効果妨害', tage: 'Anti-heal', from: ['EQ125', 'EQ127'],
    stats: { attack: 80, attack_speed_pct: 20 },
    effects: [{ id: 'lifebane', v: [0.4, 3] }, { id: 'punish', v: [0.08] }],
    passives: [
      ['生命の災い', '敵にダメージを与えると、3 秒間 対象が受けるシールドと HP 回復の効果を 40% 下げる。',
        'Lifebane', 'Dealing damage reduces the target\'s shield and HP regen effects by 40% for 3s.'],
      ['懲罰', '自分より追加 HP が多い敵ヒーローへのダメージ +8%。',
        'Punish', 'Deal 8% more damage to enemy heroes with more extra HP than you.']] },
  { id: 'EQ104', cat: 'Attack', tier: 3, price: 2030, name: 'デモンフォール', ne: 'Rose Gold Meteor', src: 'Rose Gold Meteor',
    tag: '低HP時シールド獲得', tage: 'Shield at low HP', from: ['EQ121', 'EQ132'],
    stats: { attack: 30, attack_speed_pct: 20, lifesteal_pct: 10 },
    effects: [{ id: 'dragonScale', v: [0.25, 50, 0.5] }, { id: 'lifeline', v: [0.3, 120, 0.5, 3, 60, 1] }],
    passives: [
      ['竜鱗', '追加の物理攻撃 4 につき 混合防御 +1（最大 50）。ファイター以外は半分。',
        'Dragon Scale', 'Every 4 extra physical attack grants 1 hybrid defense (up to 50). Halved for non-fighters.'],
      ['命綱', '敵ヒーローのダメージで HP が 30% を下回ると、120×レベル のシールドと、3 秒かけて減っていく 移動速度 +50% を得る（CD 60 秒）。',
        'Lifeline', 'When damage from an enemy hero drops you below 30% HP, gain a shield of 120 × level and +50% move speed decaying over 3s (60s cooldown).']] },
  { id: 'EQ105', cat: 'Attack', tier: 3, price: 2010, name: 'ハンターストライク', ne: 'Hunter Strike', src: 'Hunter Strike',
    tag: '移動速度増加', tage: 'Move speed', from: ['EQ122', 'EQ129', 'EQ133'],
    stats: { attack: 80, cooldown_reduction_pct: 10 }, unique: { armor_pen_flat: 15 },
    effects: [{ id: 'huntChase', v: [5, 0.5, 3, 8] }],
    passives: [['報復', '同じ敵ヒーロー・モンスターに 5 回続けてダメージを与えると、3 秒かけて減っていく 移動速度 +50% を得る（CD 8 秒）。',
      'Retribution', 'Damaging the same enemy hero or monster 5 times in a row grants +50% move speed decaying over 3s (8s cooldown).']] },
  { id: 'EQ106', cat: 'Attack', tier: 3, price: 3010, name: 'ディスペアブレイド', ne: 'Blade of Despair', src: 'Blade of Despair',
    tag: '最大物理攻撃', tage: 'Max physical attack', from: ['EQ125', 'EQ125'],
    stats: { attack: 160, move_speed_pct: 5 },
    effects: [{ id: 'despair', v: [0.5, 0.25, 2] }],
    passives: [['絶望', 'HP 50% 未満の敵（ミニオン以外）にダメージを与えると、2 秒間 物理攻撃 +25%（そのダメージから効く）。',
      'Despair', 'Damaging a non-minion enemy below 50% HP grants +25% physical attack for 2s (applies to that hit).']] },
  { id: 'EQ107', cat: 'Attack', tier: 3, price: 1950, name: 'オーシャンエッジ', ne: 'Blade of the Heptaseas', src: 'Blade of the Heptaseas',
    tag: 'アサシン専用', tage: 'For assassins', from: ['EQ122', 'EQ124'],
    stats: { attack: 70, hp: 250 }, unique: { armor_pen_flat: 15 },
    effects: [{ id: 'ambush', v: [5, 160, 0.4, 0.4, 1.5] }],
    passives: [['奇襲', '5 秒間 ヒーローとダメージのやり取りがないと、次の通常攻撃が 160（+総物理攻撃の 40%）の物理ダメージを追加で与え、1.5 秒間 40% 減速させる。',
      'Ambush', 'After 5s without dealing or taking hero damage, the next basic attack deals 160 (+40% total physical attack) extra physical damage and slows by 40% for 1.5s.']] },
  { id: 'EQ108', cat: 'Attack', tier: 3, price: 1880, name: 'ウィンドテラー', ne: 'Windtalker', src: 'Windtalker',
    tag: 'スプラッシュダメージ', tage: 'Splash damage', from: ['EQ123', 'EQ132'],
    stats: { attack_speed_pct: 35, crit_chance_pct: 20, move_speed: 20 },
    effects: [{ id: 'typhoon', v: [5, 0.2, 2, 3, 2, 450] }],
    passives: [['台風', '5 秒ごとに（通常攻撃 1 回で 0.2 秒短縮、最短 2 秒）、次の通常攻撃が周りの敵 最大 3 体に 150〜362（攻撃速度で増える）の魔法ダメージを与える。クリティカルあり、ミニオンには 2 倍。',
      'Typhoon', 'Every 5s (−0.2s per basic attack, min 2s), the next basic attack also hits up to 3 nearby enemies for 150–362 magic damage (scales with attack speed). Can crit; double damage to minions.']] },
  { id: 'EQ109', cat: 'Attack', tier: 3, price: 2330, name: 'エンドレスバトル', ne: 'Endless Battle', src: 'Endless Battle',
    tag: '通常攻撃強化', tage: 'Empowered attacks', from: ['EQ217', 'EQ129', 'EQ124'],
    stats: { attack: 60, hp: 250, cooldown_reduction_pct: 10, move_speed_pct: 5 },
    effects: [{ id: 'divineJustice', v: [0.6, 3, 1.5, 80, 0.4] }],
    passives: [['聖裁', 'スキル使用後 3 秒以内の次の通常攻撃が、総物理攻撃の 60% の確定ダメージを追加で与え、HP を 80（+総物理攻撃の 40%）回復する（CD 1.5 秒）。',
      'Divine Justice', 'After casting a skill, the next basic attack within 3s deals extra true damage equal to 60% total physical attack and restores 80 (+40% total physical attack) HP (1.5s cooldown).']] },
  { id: 'EQ110', cat: 'Attack', tier: 3, price: 2390, name: 'バーサーク', ne: 'Berserker\'s Fury', src: 'Berserker\'s Fury',
    tag: 'クリティカル&大ダメージ', tage: 'Crit damage', from: ['EQ125', 'EQ131', 'EQ131'],
    stats: { attack: 60, crit_chance_pct: 25 }, unique: { crit_damage_pct: 30 },
    effects: [{ id: 'doom', v: [0.12] }],
    passives: [['破滅', '通常攻撃がクリティカルになると、軽減前のダメージの 12% の確定ダメージを追加で与える。',
      'Doom', 'Critical basic attacks deal extra true damage equal to 12% of the damage before reduction.']] },
  { id: 'EQ111', cat: 'Attack', tier: 3, price: 2020, name: 'ブラッドクロウ', ne: 'Haas\'s Claws', src: 'Haas\'s Claws',
    tag: '通常攻撃吸収', tage: 'Lifesteal', from: ['EQ130', 'EQ123', 'EQ133'],
    stats: { attack: 40, attack_speed_pct: 15, crit_chance_pct: 20 }, unique: { lifesteal_pct: 20 },
    effects: [{ id: 'frenzy', v: [0.2, 2] }],
    passives: [['狂乱', 'クリティカルを出すと 2 秒間 攻撃速度 +20%。', 'Frenzy', 'Critical hits grant +20% attack speed for 2s.']] },
  { id: 'EQ112', cat: 'Attack', tier: 3, price: 2060, name: 'スピリットシャウト', ne: 'Malefic Roar', src: 'Malefic Roar',
    tag: '高物理貫通', tage: 'High physical penetration', from: ['EQ125'],
    stats: { attack: 60, armor_pen_pct: 30 },
    effects: [{ id: 'breaker', v: [0.001, 0.3] }],
    passives: [ARMOR_BUSTER,
      ['破壊者', '攻撃した敵の物理防御 1 につき 物理貫通 +0.1%（最大 +30%）。',
        'Breaker', '+0.1% physical penetration per point of the target\'s physical defense (up to +30%).']] },
  { id: 'EQ113', cat: 'Attack', tier: 3, price: 1910, name: 'ウィンタークラウン', ne: 'Winter Crown', src: 'Winter Crown',
    tag: '短時間無敵', tage: 'Brief invulnerability', also: ['Magic'], from: ['EQ128', 'EQ320', 'EQ324'],
    stats: { adaptive_attack: 45, hp: 400, cooldown_reduction_pct: 5 },
    effects: [{ id: 'frozen', v: [2, 100] }],
    passives: [['凍結', '（アクティブ）2 秒間 凍りついて、狙われず ダメージを受けない。その間は移動もスキルもできない（CD 100 秒）。',
      'Frozen', '(Active) Freeze for 2s: untargetable and immune to damage, but unable to move or cast (100s cooldown).']] },
  { id: 'EQ114', cat: 'Attack', tier: 3, price: 2050, name: 'フリーティングタイム', ne: 'Fleeting Time', src: 'Fleeting Time',
    tag: 'SPスキルCD短縮', tage: 'Ultimate cooldown', also: ['Magic', 'Defense'], from: ['EQ320', 'EQ320', 'EQ128'],
    stats: { adaptive_attack: 70, hp: 600, cooldown_reduction_pct: 15 },
    effects: [{ id: 'timestream', v: [0.3] }],
    passives: [['刹那', 'キルまたはアシストを獲得すると、必殺技の残りクールダウンを 30% 短縮する。',
      'Timestream', 'Kills and assists cut the ultimate\'s remaining cooldown by 30%.']] },
  { id: 'EQ115', cat: 'Attack', tier: 3, price: 1500, name: '天空の刃', ne: 'Sky Piercer', src: 'Sky Piercer',
    tag: 'フィニッシャー推奨', tage: 'Finisher', also: ['Magic'], from: ['EQ128', 'EQ128'],
    stats: { adaptive_attack: 60, move_speed: 15 },
    effects: [{ id: 'lethality', v: [0.04, 0.001, 10, 0.3, 80] }],
    passives: [['致死', '敵ヒーローにダメージを与えたとき HP が 4% 未満なら、シールドを無視して倒す。キルで「致死」を 10 得て（最大 80）、1 につき しきい値 +0.1%。倒されると 30% を失う。',
      'Lethality', 'Damaging an enemy hero below 4% HP executes them (ignores shields). Kills grant 10 Lethality stacks (max 80), each +0.1% threshold; lose 30% of stacks on death.']] },
  { id: 'EQ116', cat: 'Attack', tier: 3, price: 2100, name: '常勝の神斧', ne: 'War Axe', src: 'War Axe',
    tag: '継続的にダメージ増加', tage: 'Ramping damage', from: ['EQ124', 'EQ129', 'EQ320'],
    stats: { attack: 35, hp: 400, cooldown_reduction_pct: 10, lifesteal_pct: 8, spell_vamp_pct: 8 },
    effects: [{ id: 'fightingSpirit', v: [12, 4, 6, 0.1, 0.5, 1] }],
    passives: [['闘志', 'ダメージを与えると、1 秒ごとに 4 秒間 物理攻撃 +12（最大 6 回、+72）。最大のときは与えたダメージの 10% の確定ダメージを追加で与える。射手・メイジ・サポートは効果が半分。',
      'Fighting Spirit', 'Dealing damage grants +12 physical attack for 4s, once per second (up to 6 stacks, +72). At full stacks, deal extra true damage equal to 10% of damage dealt. Halved for marksmen, mages and supports.']] },
  { id: 'EQ117', cat: 'Attack', tier: 3, price: 1910, name: 'ナチュラルウィンド', ne: 'Wind of Nature', src: 'Wind of Nature',
    tag: '物理ダメージ無効化', tage: 'Physical immunity', from: ['EQ127', 'EQ130'],
    stats: { attack: 30, attack_speed_pct: 20, lifesteal_pct: 10 },
    effects: [{ id: 'windChant', v: [2, 90, 0.5] }],
    passives: [['風の歌', '（アクティブ）2 秒間 物理ダメージを受けない。射手以外は 1 秒（CD 90 秒）。',
      'Wind Chant', '(Active) Become immune to physical damage for 2s (1s for non-marksmen; 90s cooldown).']] },
  { id: 'EQ118', cat: 'Attack', tier: 3, price: 2000, name: '如意棒', ne: 'Golden Staff', src: 'Golden Staff',
    tag: '通常攻撃強化', tage: 'Empowered attacks', from: ['EQ127', 'EQ133', 'EQ133'],
    stats: { attack: 55, attack_speed_pct: 15 },
    effects: [{ id: 'goldenStaff', v: [1, 2, 0.8, 2] }],
    passives: [
      ['迅速', '追加のクリティカル率 1% を 攻撃速度 +1% に変える（クリティカルは出なくなる）。',
        'Swift', 'Each 1% extra crit chance becomes +1% attack speed (you can no longer crit).'],
      ['無尽の打撃', 'クリティカルでない通常攻撃 2 回ごとに、次の通常攻撃の攻撃速度 +80%、命中時の効果が 2 回多く発動する。',
        'Endless Strike', 'After every 2 non-crit basic attacks, the next one gains +80% attack speed and triggers attack effects 2 extra times.']] },
  { id: 'EQ119', cat: 'Attack', tier: 3, price: 2050, name: 'ラスティサイズ', ne: 'Corrosion Scythe', src: 'Corrosion Scythe',
    tag: '通常移動速度低下', tage: 'Slowing attacks', from: ['EQ126', 'EQ127'],
    stats: { attack: 30, attack_speed_pct: 30, move_speed_pct: 5 },
    effects: [{ id: 'corrosive', v: [80, 0.08, 0.5, 1.5, 5] }, { id: 'impulse', v: [0.06, 3, 5] }],
    passives: [
      ['腐食', '通常攻撃が 80 の物理ダメージを追加で与え、1.5 秒間 8% 減速させる（遠隔は半分。5 回まで重なる）。',
        'Corrosive', 'Basic attacks deal 80 extra physical damage and slow by 8% for 1.5s (halved for ranged; stacks 5 times).'],
      ['衝動', '通常攻撃のたびに 3 秒間 攻撃速度 +6%（5 回まで、+30%）。',
        'Impulse', 'Basic attacks grant +6% attack speed for 3s (up to 5 stacks, +30%).']] },
  { id: 'EQ120', cat: 'Attack', tier: 3, price: 2180, name: 'デモンハント', ne: 'Demon Hunter Sword', src: 'Demon Hunter Sword',
    tag: 'タンク対策', tage: 'Anti-tank', from: ['EQ127', 'EQ130', 'EQ132'],
    stats: { attack: 35, attack_speed_pct: 20 },
    effects: [{ id: 'engulf', v: [0.08, 60] }, { id: 'devour', v: [10, 4, 0.5] }],
    passives: [
      ['侵食', '通常攻撃が、対象の現在 HP の 8% の物理ダメージを追加で与える（ミニオンには最大 60）。',
        'Engulf', 'Basic attacks deal extra physical damage equal to 8% of the target\'s current HP (max 60 against minions).'],
      ['貪食', '通常攻撃のたびに HP を 10（+4×レベル）回復する（ミニオンには半分）。',
        'Devour', 'Each basic attack restores 10 (+4 × level) HP (halved against minions).']] },
  // 素材・ポーション
  { id: 'EQ121', cat: 'Attack', tier: 2, price: 1050, name: 'マジックブレイド', ne: 'Magic Blade', src: 'Magic Blade',
    from: ['EQ133', 'EQ130'], stats: { attack: 35, lifesteal_pct: 10 },
    effects: [{ id: 'lifeline', v: [0.3, 60, 0.5, 3, 60, 0] }],
    passives: [['命綱', 'HP が 30% を下回ると、60×レベル のシールドと、3 秒かけて減っていく 移動速度 +50% を得る（CD 60 秒）。',
      'Lifeline', 'When you drop below 30% HP, gain a shield of 60 × level and +50% move speed decaying over 3s (60s cooldown).']] },
  { id: 'EQ122', cat: 'Attack', tier: 2, price: 830, name: 'レイシハンマー', ne: 'Fury Hammer', src: 'Fury Hammer',
    from: ['EQ133'], stats: { attack: 35 }, unique: { armor_pen_flat: 12 } },
  { id: 'EQ123', cat: 'Attack', tier: 2, price: 900, name: 'ワイルドメテオ', ne: 'Rogue Meteor', src: 'Rogue Meteor',
    from: ['EQ132', 'EQ131'], stats: { attack_speed_pct: 15, crit_chance_pct: 10 } },
  { id: 'EQ124', cat: 'Attack', tier: 2, price: 650, name: 'オーガアックス', ne: 'Ogre Tomahawk', src: 'Ogre Tomahawk',
    from: ['EQ133', 'EQ324'], stats: { attack: 25, hp: 230 } },
  { id: 'EQ125', cat: 'Attack', tier: 2, price: 910, name: 'レギオンソード', ne: 'Legion Sword', src: 'Legion Sword',
    from: ['EQ133', 'EQ133'], stats: { attack: 60 } },
  { id: 'EQ126', cat: 'Attack', tier: 2, price: 1000, name: 'スイフトクロスボウ', ne: 'Swift Crossbow', src: 'Swift Crossbow',
    from: ['EQ132', 'EQ132'], stats: { attack_speed_pct: 20 },
    effects: [{ id: 'crossbow', v: [40] }, { id: 'impulse', v: [0.03, 3, 5] }],
    passives: [
      ['連弩', '通常攻撃が 40 の適応ダメージを追加で与える。', 'Crossbow', 'Basic attacks deal 40 extra adaptive damage.'],
      ['衝動', '通常攻撃のたびに 3 秒間 攻撃速度 +3%（5 回まで、+15%）。',
        'Impulse', 'Basic attacks grant +3% attack speed for 3s (up to 5 stacks, +15%).']] },
  { id: 'EQ127', cat: 'Attack', tier: 2, price: 600, name: 'ロングスピア', ne: 'Regular Spear', src: 'Regular Spear',
    from: ['EQ132', 'EQ133'], stats: { attack: 20, attack_speed_pct: 10 } },
  { id: 'EQ128', cat: 'Attack', tier: 1, price: 500, name: 'エキスパートグローブ', ne: 'Expert Gloves', src: 'Expert Gloves',
    also: ['Magic'], stats: { adaptive_attack: 30 } },
  { id: 'EQ129', cat: 'Attack', tier: 1, price: 450, name: 'ハンティングボウ', ne: 'Iron Hunting Bow', src: 'Iron Hunting Bow',
    stats: { attack: 10, cooldown_reduction_pct: 5 } },
  { id: 'EQ130', cat: 'Attack', tier: 1, price: 400, name: 'ヴァンパイアハンマー', ne: 'Vampire Mallet', src: 'Vampire Mallet',
    stats: { attack: 8, lifesteal_pct: 8 } },
  { id: 'EQ131', cat: 'Attack', tier: 1, price: 320, name: 'ジャベリン', ne: 'Javelin', src: 'Javelin', stats: { crit_chance_pct: 8 } },
  { id: 'EQ132', cat: 'Attack', tier: 1, price: 280, name: 'ナイフ', ne: 'Knife', src: 'Knife', stats: { attack_speed_pct: 10 } },
  { id: 'EQ133', cat: 'Attack', tier: 1, price: 250, name: 'ダガー', ne: 'Dagger', src: 'Dagger', stats: { attack: 15 } },
  { id: 'EQ134', cat: 'Attack', tier: 1, price: 1500, name: 'パワーポーション', ne: 'Power Potion', src: 'Power Potion',
    consumable: 120, stats: { attack: 30, lifesteal_pct: 15 },
    passives: [['パワー増強', '買うとすぐに使われ、120 秒間 物理攻撃 +30、ライフスティール +15%。所持枠を使わない。ポーションの効果は 1 つだけ。',
      'Increase Power', 'Used on purchase: +30 physical attack and +15% lifesteal for 120s. Takes no slot; only one potion effect at a time.']] },

  // ───────────────────────────── 魔法 ─────────────────────────────
  { id: 'EQ201', cat: 'Magic', tier: 3, price: 2250, name: 'ウィッシュランタン', ne: 'Wishing Lantern', src: 'Wishing Lantern',
    tag: '高HP対策', tage: 'Anti high HP', from: ['EQ219', 'EQ221', 'EQ223'],
    stats: { ability_power: 75, mana: 400, cooldown_reduction_pct: 10 },
    effects: [{ id: 'butterfly', v: [900, 0.08, 50] }],
    passives: [['アゲハチョウ', '敵ヒーローに 900 の魔法ダメージを与える（ダメージ軽減前に計算）ごとにアゲハチョウを召喚し、その敵に 現在 HP の 8%（最低 50）の魔法ダメージを与える。',
      'Butterfly Goddess', 'For every 900 magic damage dealt to enemy heroes (before reduction), summon a butterfly that deals magic damage equal to 8% of the target\'s current HP (min 50).']] },
  { id: 'EQ202', cat: 'Magic', tier: 3, price: 1850, name: 'オアシスのフラスコ', ne: 'Flask of the Oasis', src: 'Flask of the Oasis',
    tag: '味方保護', tage: 'Protects allies', from: ['EQ219', 'EQ221', 'EQ324'],
    stats: { ability_power: 60, hp: 300, cooldown_reduction_pct: 10 }, unique: { heal_shield_power_pct: 12 },
    effects: [{ id: 'oasisBlessing', v: [0.35, 100, 3, 2, 60] }],
    passives: [['祝福', '与える回復・シールド +12%（固有）。味方を回復・シールドしたとき、その味方の HP が 35% 未満なら、100×レベル のシールドを 3 秒間 与え、自分のスキルのクールダウンを 2 秒 短縮する（同じ味方には 60 秒に 1 回）。',
      'Blessing', '+12% healing effect (unique). Healing or shielding an ally below 35% HP also gives them a shield of 100 × level for 3s and cuts your skill cooldowns by 2s (once per 60s per ally).']] },
  { id: 'EQ203', cat: 'Magic', tier: 3, price: 2000, name: 'ジーニアスワンド', ne: 'Genius Wand', src: 'Genius Wand',
    tag: '魔法防御低下', tage: 'Magic defense shred', from: ['EQ216', 'EQ219'],
    stats: { ability_power: 75, move_speed_pct: 5 }, unique: { magic_pen_flat: 10 },
    effects: [{ id: 'geniusShred', v: [2.5, 0.5, 3, 2] }],
    passives: [['魔力', '魔法貫通 +10（固有）。敵ヒーローに魔法ダメージを与えると、2 秒間 魔法防御を 2.5（+0.5×レベル）下げる（3 回まで重なる）。',
      'Magic', '+10 magic penetration (unique). Magic damage to an enemy hero lowers its magic defense by 2.5 (+0.5 × level) for 2s (stacks 3 times).']] },
  { id: 'EQ204', cat: 'Magic', tier: 3, price: 2250, name: 'ボルトロッド', ne: 'Lightning Truncheon', src: 'Lightning Truncheon',
    tag: 'スキル発動時に範囲ダメージ発生', tage: 'Skill burst', from: ['EQ219', 'EQ221', 'EQ223'],
    stats: { ability_power: 75, mana: 400, cooldown_reduction_pct: 10 },
    effects: [{ id: 'resonate', v: [6, 255, 0.85] }],
    passives: [['共鳴', '6 秒ごとに、次にダメージを与えるスキルが、当たった敵すべてに 255（+総魔法攻撃の 85%）の魔法ダメージを追加で与える。',
      'Resonate', 'Every 6s, the next damaging skill deals 255 (+85% total magic power) extra magic damage to every enemy it hits.']] },
  { id: 'EQ205', cat: 'Magic', tier: 3, price: 2110, name: 'ブラッドウィング', ne: 'Blood Wings', src: 'Blood Wings',
    tag: 'シールド加速', tage: 'Shield & speed', from: ['EQ219', 'EQ219'],
    stats: { ability_power: 90 },
    effects: [{ id: 'guardWings', v: [800, 1.0, 20, 30, 150, 1] }],
    passives: [['守護', '800（+総魔法攻撃の 100%）のシールドを得る。最後にダメージを受けてから 20 秒で張り直す。シールドがある間は移動速度 +30、割れると 1 秒間 移動速度 +150。',
      'Guard', 'Gain a shield of 800 (+100% total magic power), restored 20s after you last took damage. +30 move speed while it holds; +150 move speed for 1s when it breaks.']] },
  { id: 'EQ206', cat: 'Magic', tier: 3, price: 2120, name: '星の大鎌', ne: 'Starlium Scythe', src: 'Starlium Scythe',
    tag: '通常物理強化', tage: 'Empowered attacks', from: ['EQ217', 'EQ221', 'EQ219'],
    stats: { ability_power: 75, cooldown_reduction_pct: 10, lifesteal_pct: 8, spell_vamp_pct: 8, resource_regen: 6 },
    effects: [{ id: 'crisis', v: [90, 0.6, 3, 1.5, 0.15, 1.5] }],
    passives: [['危機', 'スキル使用後 3 秒以内の次の通常攻撃が 90（+総魔法攻撃の 60%）の確定ダメージを追加で与え、1.5 秒間 15% 減速させる（CD 1.5 秒）。',
      'Crisis', 'After casting a skill, the next basic attack within 3s deals 90 (+60% total magic power) extra true damage and slows by 15% for 1.5s (1.5s cooldown).']] },
  { id: 'EQ207', cat: 'Magic', tier: 3, price: 2050, name: 'ヒートロッド', ne: 'Glowing Wand', src: 'Glowing Wand',
    tag: '治療低下', tage: 'Burn & anti-heal', from: ['EQ216', 'EQ224', 'EQ324'],
    stats: { ability_power: 60, hp: 300, move_speed_pct: 5 },
    effects: [{ id: 'scorch', v: [3, 0.01] }, { id: 'lifebane', v: [0.4, 3] }],
    passives: [
      ['焼灼', '魔法ダメージを与えると 3 秒間 燃やし、毎秒 最大 HP の 1% の魔法ダメージを与える。',
        'Scorch', 'Magic damage burns the target for 3s, dealing magic damage equal to 1% of its max HP per second.'],
      ['生命の災い', '敵にダメージを与えると、3 秒間 対象が受けるシールドと HP 回復の効果を 40% 下げる。',
        'Lifebane', 'Dealing damage reduces the target\'s shield and HP regen effects by 40% for 3s.']] },
  { id: 'EQ208', cat: 'Magic', tier: 3, price: 2040, name: 'フロスト', ne: 'Ice Queen Wand', src: 'Ice Queen Wand',
    tag: 'スキルが命中した敵を減速させる', tage: 'Slowing skills', from: ['EQ220', 'EQ216', 'EQ224'],
    stats: { ability_power: 60, hp: 300, spell_vamp_pct: 10, move_speed_pct: 7 },
    effects: [{ id: 'iceBound', v: [0.10, 2, 3] }],
    passives: [['氷結', 'スキルで敵ヒーローにダメージを与えると 2 秒間 10% 減速させる（3 回まで重なる、30%）。',
      'Ice Bound', 'Skill damage to an enemy hero slows it by 10% for 2s (stacks 3 times, 30%).']] },
  { id: 'EQ209', cat: 'Magic', tier: 3, price: 2020, name: '濃縮エネルギー', ne: 'Concentrated Energy', src: 'Concentrated Energy',
    tag: '継続的にダメージ増加', tage: 'Ramping damage', from: ['EQ220', 'EQ219', 'EQ324'],
    stats: { ability_power: 75, hp: 400 }, unique: { lifesteal_pct: 20, spell_vamp_pct: 20 },
    effects: [{ id: 'recharge', v: [5, 6, 0.4, 0.12, 5] }],
    passives: [['充填', '混合吸血 +20%（固有）。魔法ダメージを与えると 魔法攻撃 +5（6 回まで、+30。0.4 秒に 1 回）。最大のときは 5 秒間 与える魔法ダメージ +12%。',
      'Recharge', '+20% hybrid lifesteal (unique). Dealing magic damage grants +5 magic power (up to 6 stacks, +30; once per 0.4s). At full stacks, magic damage dealt is increased by 12% for 5s.']] },
  { id: 'EQ210', cat: 'Magic', tier: 3, price: 3000, name: 'ガーディアンレリック', ne: 'Holy Crystal', src: 'Holy Crystal',
    tag: '最大魔法攻撃', tage: 'Max magic power', from: ['EQ219', 'EQ219', 'EQ219'],
    stats: { ability_power: 165 },
    effects: [{ id: 'mystery', v: [0.20, 0.01] }],
    passives: [['神秘', '総魔法攻撃 +21〜35%（レベル 1 につき +1%）。',
      'Mystery', 'Total magic power +21–35% (+1% per hero level).']] },
  { id: 'EQ211', cat: 'Magic', tier: 3, price: 1970, name: '魔法の聖剣', ne: 'Divine Glaive', src: 'Divine Glaive',
    tag: '魔法貫通', tage: 'Magic penetration', from: ['EQ219'],
    stats: { ability_power: 65, magic_pen_pct: 40 },
    effects: [{ id: 'spellbreaker', v: [0.001, 0.2] }],
    passives: [['魔法破り', '魔法貫通 +40%（固有）。攻撃した敵の魔法防御 1 につき 魔法貫通 +0.1%（最大 +20%）。',
      'Spellbreaker', '+40% magic penetration (unique). +0.1% magic penetration per point of the target\'s magic defense (up to +20%).']] },
  { id: 'EQ212', cat: 'Magic', tier: 3, price: 2030, name: 'デスティニー', ne: 'Clock of Destiny', src: 'Clock of Destiny',
    tag: '魔法タンク専用', tage: 'For magic tanks', from: ['EQ215', 'EQ221', 'EQ221'],
    stats: { ability_power: 45, hp: 400, mana: 400, cooldown_reduction_pct: 10 },
    effects: [{ id: 'destiny', v: [4.5, 0.5, 5, 6, 0.4] }, { id: 'gift', v: [0.5, 0.15, 3, 60] }],
    passives: [
      ['運命', '敵ヒーローに魔法ダメージを与えると 5 秒間 混合防御 +4.5（+0.5×レベル）（6 回まで。0.4 秒に 1 回）。',
        'Destiny', 'Magic damage to an enemy hero grants 4.5 (+0.5 × level) hybrid defense for 5s (up to 6 stacks; once per 0.4s).'],
      ['贈り物', 'HP が 50% を下回ると 3 秒かけて最大 HP の 15% を、MP が 50% を下回ると 3 秒かけて最大 MP の 15% を回復する（CD 60 秒）。',
        'Gift', 'Dropping below 50% HP restores 15% max HP over 3s; dropping below 50% mana restores 15% max mana over 3s (60s cooldown).']] },
  { id: 'EQ213', cat: 'Magic', tier: 3, price: 2030, name: 'ヘヴンウィング', ne: 'Feather of Heaven', src: 'Feather of Heaven',
    tag: '通常攻撃強化', tage: 'Empowered attacks', from: ['EQ126', 'EQ221'],
    stats: { ability_power: 60, attack_speed_pct: 20, lifesteal_pct: 10, cooldown_reduction_pct: 5 },
    effects: [{ id: 'affliction', v: [50, 0.3] }, { id: 'impulse', v: [0.06, 3, 5] }],
    passives: [
      ['苦痛', '通常攻撃が 50（+総魔法攻撃の 30%）の魔法ダメージを追加で与える。',
        'Affliction', 'Basic attacks deal 50 (+30% total magic power) extra magic damage.'],
      ['衝動', '通常攻撃のたびに 3 秒間 攻撃速度 +6%（5 回まで、+30%）。',
        'Impulse', 'Basic attacks grant +6% attack speed for 3s (up to 5 stacks, +30%).']] },
  { id: 'EQ214', cat: 'Magic', tier: 3, price: 2070, name: 'タリスマン', ne: 'Enchanted Talisman', src: 'Enchanted Talisman',
    tag: 'MP回復&CD短縮', tage: 'Mana & cooldown', from: ['EQ218', 'EQ222', 'EQ219'],
    stats: { ability_power: 75, hp: 300, cooldown_reduction_pct: 15 },
    effects: [{ id: 'manaSpring', v: [0.015] }, { id: 'magicMastery', v: [0.05] }],
    passives: [
      ['魔力の泉', '毎秒 最大 MP の 1.5% を回復する。', 'Mana Spring', 'Restores 1.5% of max mana per second.'],
      ['魔法の極意', 'クールダウン短縮の上限 +5%（40% → 45%）。', 'Magic Mastery', 'Cooldown reduction cap +5% (40% → 45%).']] },
  // 素材・ポーション
  { id: 'EQ215', cat: 'Magic', tier: 2, price: 700, name: 'エレガントジェム', ne: 'Elegant Gem', src: 'Elegant Gem',
    from: ['EQ223', 'EQ324'], stats: { hp: 300, mana: 380 },
    effects: [{ id: 'gift', v: [0.5, 0.15, 3, 60] }],
    passives: [['贈り物', 'HP が 50% を下回ると 3 秒かけて最大 HP の 15% を、MP が 50% を下回ると 3 秒かけて最大 MP の 15% を回復する（CD 60 秒）。',
      'Gift', 'Dropping below 50% HP restores 15% max HP over 3s; dropping below 50% mana restores 15% max mana over 3s (60s cooldown).']] },
  { id: 'EQ216', cat: 'Magic', tier: 2, price: 660, name: 'エキゾチックベール', ne: 'Exotic Veil', src: 'Exotic Veil',
    from: ['EQ224'], stats: { ability_power: 30, move_speed_pct: 5 } },
  { id: 'EQ217', cat: 'Magic', tier: 2, price: 600, name: 'アズールブレイド', ne: 'Azure Blade', src: 'Azure Blade',
    from: ['EQ222', 'EQ222'], stats: { resource_regen: 5, cooldown_reduction_pct: 5 },
    effects: [{ id: 'judgement', v: [50, 3, 1.5] }],
    passives: [['審判', 'スキル使用後 3 秒以内の次の通常攻撃が 50 の確定ダメージを追加で与える（CD 1.5 秒）。',
      'Judgement', 'After casting a skill, the next basic attack within 3s deals 50 extra true damage (1.5s cooldown).']] },
  { id: 'EQ218', cat: 'Magic', tier: 2, price: 950, name: '邪悪な法典', ne: 'Tome of Evil', src: 'Tome of Evil',
    from: ['EQ222', 'EQ221'], stats: { ability_power: 30, resource_regen: 2, cooldown_reduction_pct: 10 } },
  { id: 'EQ219', cat: 'Magic', tier: 2, price: 820, name: 'マジックワンド', ne: 'Magic Wand', src: 'Magic Wand',
    from: ['EQ224'], stats: { ability_power: 45 } },
  { id: 'EQ220', cat: 'Magic', tier: 2, price: 500, name: 'ミスティックコンテナー', ne: 'Mystic Container', src: 'Mystic Container',
    from: ['EQ224'], stats: { ability_power: 15, spell_vamp_pct: 8 } },
  { id: 'EQ221', cat: 'Magic', tier: 1, price: 450, name: '賢者の書', ne: 'Book of Sages', src: 'Book of Sages',
    stats: { ability_power: 8, cooldown_reduction_pct: 5 } },
  { id: 'EQ222', cat: 'Magic', tier: 1, price: 120, name: 'マジックネックレス', ne: 'Magic Necklace', src: 'Magic Necklace',
    stats: { resource_regen: 2 } },
  { id: 'EQ223', cat: 'Magic', tier: 1, price: 220, name: 'パワークリスタル', ne: 'Power Crystal', src: 'Power Crystal',
    stats: { mana: 280 } },
  { id: 'EQ224', cat: 'Magic', tier: 1, price: 300, name: 'ミスティックブック', ne: 'Mystery Codex', src: 'Mystery Codex',
    stats: { ability_power: 15 } },
  { id: 'EQ225', cat: 'Magic', tier: 1, price: 1500, name: 'マジックポーション', ne: 'Magic Potion', src: 'Magic Potion',
    consumable: 120, stats: { ability_power: 30, cooldown_reduction_pct: 10 },
    passives: [['魔力増強', '買うとすぐに使われ、120 秒間 魔法攻撃 +30、クールダウン短縮 +10%。所持枠を使わない。ポーションの効果は 1 つだけ。',
      'Increase Power', 'Used on purchase: +30 magic power and +10% cooldown reduction for 120s. Takes no slot; only one potion effect at a time.']] },

  // ───────────────────────────── 防御 ─────────────────────────────
  { id: 'EQ301', cat: 'Defense', tier: 3, price: 1880, name: '聖光の鎧', ne: 'Radiant Armor', src: 'Radiant Armor',
    tag: '魔法ダメージ軽減', tage: 'Magic damage reduction', from: ['EQ317', 'EQ322', 'EQ321'],
    stats: { hp: 950, magic_resist: 40, hp_regen: 12 },
    effects: [{ id: 'holyBlessing', v: [5, 1, 5, 6, 0.4] }],
    passives: [['聖なる加護', '魔法ダメージを受けると 5 秒間 魔法防御 +5（+1×レベル）（6 回まで。0.4 秒に 1 回）。',
      'Holy Blessing', 'Taking magic damage grants 5 (+1 × level) magic defense for 5s (up to 6 stacks; once per 0.4s).']] },
  { id: 'EQ302', cat: 'Defense', tier: 3, price: 2100, name: '懲罰の肩甲', ne: 'Chastise Pauldron', src: 'Chastise Pauldron',
    tag: '敵攻撃速度低下', tage: 'Slows enemy attacks', from: ['EQ314', 'EQ319'],
    stats: { hp: 900, armor: 40 },
    effects: [{ id: 'chastise', v: [0.25, 2] }, { id: 'redemption', v: [0.3, 0.2, 2, 60] }],
    passives: [
      ['懲罰', 'ダメージを受けると、攻撃した敵の攻撃速度を 2 秒間 25% 下げる。',
        'Chastise', 'Taking damage lowers the attacker\'s attack speed by 25% for 2s.'],
      ['贖罪', 'ダメージで HP が 30% を下回ると、2 秒かけて最大 HP の 20% を回復する（CD 60 秒）。',
        'Redemption', 'When damage drops you below 30% HP, recover 20% max HP over 2s (60s cooldown).']] },
  { id: 'EQ303', cat: 'Defense', tier: 3, price: 2070, name: 'ブレストプレート', ne: 'Brute Force Breastplate', src: 'Brute Force Breastplate',
    tag: '攻撃&移動速度上昇、コントロール時間短縮', tage: 'Damage, speed & CC reduction', from: ['EQ319', 'EQ320', 'EQ323'],
    stats: { hp: 800, armor: 20, cooldown_reduction_pct: 10 },
    effects: [{ id: 'bruteForce', v: [8, 0.02, 4, 6, 0.25, 1] }],
    passives: [['暴力', 'ダメージを与えると、1 秒ごとに 4 秒間 適応攻撃 +8・移動速度 +2%（6 回まで）。最大のときはコントロール時間短縮 +25%。',
      'Brute Force', 'Dealing damage grants +8 adaptive attack and +2% move speed for 4s, once per second (up to 6 stacks). At full stacks, gain +25% CC reduction.']] },
  { id: 'EQ304', cat: 'Defense', tier: 3, price: 2120, name: 'イモータル', ne: 'Immortality', src: 'Immortality',
    tag: '復活', tage: 'Revive', from: ['EQ319', 'EQ324', 'EQ323'],
    stats: { hp: 850, armor: 15 },
    effects: [{ id: 'immortal', v: [2.5, 0.16, 150, 70, 3, 210] }],
    passives: [['不滅', '倒されると 2.5 秒後にその場で復活し、最大 HP の 16% と、150（+70×レベル）のシールドを 3 秒間 得る（CD 210 秒）。',
      'Immortal', 'On death, revive after 2.5s with 16% max HP and a shield of 150 (+70 × level) for 3s (210s cooldown).']] },
  { id: 'EQ305', cat: 'Defense', tier: 3, price: 2010, name: 'ドミナントシールド', ne: 'Dominance Ice', src: 'Dominance Ice',
    tag: '回復減少', tage: 'Anti-heal aura', from: ['EQ316', 'EQ323', 'EQ322'],
    stats: { armor: 40, magic_resist: 40, move_speed_pct: 5 },
    effects: [{ id: 'fortress', v: [8, 40, 500] }, { id: 'lifebaneAura', v: [500, 0.4] }],
    passives: [
      ['要塞の盾', '周り（5 マス）の敵ヒーロー 1 体につき 混合防御 +8（最大 +40）。',
        'Fortress Shield', '+8 hybrid defense per enemy hero within 5 units (up to +40).'],
      ['生命の災い', '周り（5 マス）の敵が受けるシールドと HP 回復の効果を 40% 下げる。',
        'Lifebane', 'Enemies within 5 units have their shield and HP regen effects reduced by 40%.']] },
  { id: 'EQ306', cat: 'Defense', tier: 3, price: 2150, name: 'ヴァルキュリアブレス', ne: 'Valkyrie\'s Shield', src: 'Athena\'s Shield (Valkyrie\'s Shield)',
    tag: '魔法ダメージ耐性', tage: 'Magic damage resistance', from: ['EQ317', 'EQ324'],
    stats: { hp: 900, magic_resist: 48, hp_regen: 2 },
    effects: [{ id: 'valkyrie', v: [0.25, 3, 5] }],
    passives: [['守護の盾', '敵ヒーローのスキル・通常攻撃で魔法ダメージを受けると、3 秒間 受ける魔法ダメージ −25%（そのダメージから効く）。戦闘を離れて 5 秒で再び使える。',
      'Shield', 'Taking magic damage from an enemy hero\'s skill or basic attack reduces magic damage taken by 25% for 3s (including that hit). Recharges 5s after leaving combat.']] },
  { id: 'EQ307', cat: 'Defense', tier: 3, price: 1860, name: 'オラクル', ne: 'Oracle', src: 'Oracle',
    tag: '回復向上', tage: 'Healing received', from: ['EQ320', 'EQ320', 'EQ324'],
    stats: { hp: 850, armor: 20, magic_resist: 20, cooldown_reduction_pct: 10, heal_received_pct: 25 },
    passives: [['祝福', '受けるシールドと HP 回復の効果 +25%。', 'Bless', 'Shield and HP regen effects received +25%.']] },
  { id: 'EQ308', cat: 'Defense', tier: 3, price: 2170, name: '上古の鎧', ne: 'Antique Cuirass', src: 'Antique Cuirass',
    tag: '物理攻撃弱体化', tage: 'Weakens physical damage', from: ['EQ315', 'EQ319'],
    stats: { hp: 920, armor: 40, hp_regen: 4 },
    effects: [{ id: 'deter', v: [0.06, 2, 3] }],
    passives: [['威嚇', 'スキルを受けると、攻撃者の物理ダメージを 2 秒間 6% 低下させる。最大 3 スタック。',
      'Deter', 'When hit by an enemy skill, the attacker\'s physical damage is reduced by 6% for 2s (up to 3 stacks).']] },
  { id: 'EQ309', cat: 'Defense', tier: 3, price: 2500, name: '守り人の兜', ne: 'Guardian Helmet', src: 'Guardian Helmet',
    tag: 'HP持続回復', tage: 'HP regen', from: ['EQ319', 'EQ319', 'EQ319'],
    stats: { hp: 1800, hp_regen: 20 },
    effects: [{ id: 'recovery', v: [5, 0.025] }, { id: 'defender', v: [500, 30, 0.003] }],
    passives: [
      ['回復', '戦闘を離れて 5 秒たつと、毎秒 最大 HP の 2.5% を回復する。',
        'Recovery', 'After 5s out of combat, recover 2.5% of max HP per second.'],
      ['守り手', '1 回で 500 を超えるダメージを受けると、超えた分の（30 + 最大 HP の 0.3%）% の HP を回復する。',
        'Defender', 'When a single hit deals more than 500 damage, recover (30 + 0.3% of max HP)% of the excess as HP.']] },
  { id: 'EQ310', cat: 'Defense', tier: 3, price: 1910, name: 'カースヘルム', ne: 'Cursed Helmet', src: 'Cursed Helmet',
    tag: '継続ダメージ', tage: 'Damage aura', from: ['EQ318', 'EQ319', 'EQ322'],
    stats: { hp: 1200, magic_resist: 20 },
    effects: [{ id: 'burningSoul', v: [0.012, 1.25, 0.15, 350] }, { id: 'curse', v: [3, 3, 3] }],
    passives: [
      ['燃える魂', '周りの敵に 毎秒 最大 HP の 1.2% の魔法ダメージを与える。ミニオン・モンスターには +125%（+15%×レベル）。',
        'Burning Soul', 'Deal magic damage equal to 1.2% of your max HP per second to nearby enemies; +125% (+15% × level) against minions and monsters.'],
      ['呪い', '燃える魂でダメージを与えた敵の混合防御を 3 秒間 3 下げる（3 回まで）。',
        'Curse', 'Burning Soul damage lowers the target\'s hybrid defense by 3 for 3s (up to 3 stacks).']] },
  { id: 'EQ311', cat: 'Defense', tier: 3, price: 1820, name: 'サンダーベルト', ne: 'Thunder Belt', src: 'Thunder Belt',
    tag: 'タンク用追加ダメージ', tage: 'Tank damage', from: ['EQ319', 'EQ323', 'EQ322'],
    stats: { hp: 600, armor: 15, magic_resist: 15, move_speed: 20 },
    effects: [{ id: 'thunderbolt', v: [4, 50, 1, 1, 0.99, 0.3, 250, 0.5] }],
    passives: [['雷撃', '4 秒ごとに、次の通常攻撃が 対象と周りの敵に 50（+追加物理防御の 100%）（+追加魔法防御の 100%）の確定ダメージを与え、一瞬 99% 減速させる。敵ヒーローに当たるたびに混合防御が永久に +1。射手・メイジ・アサシンは効果が半分。',
      'Thunderbolt', 'Every 4s, the next basic attack deals 50 (+100% extra physical defense) (+100% extra magic defense) true damage to the target and nearby enemies and briefly slows them by 99%. Each enemy hero hit permanently grants +1 hybrid defense. Halved for marksmen, mages and assassins.']] },
  { id: 'EQ312', cat: 'Defense', tier: 3, price: 2250, name: 'クイーンズウイング', ne: 'Queen\'s Wings', src: 'Queen\'s Wings',
    tag: '低HP時反撃', tage: 'Low HP counter', from: ['EQ319', 'EQ320', 'EQ128'],
    stats: { hp: 750, adaptive_attack: 30, cooldown_reduction_pct: 10, spell_vamp_pct: 10 },
    effects: [{ id: 'demonize', v: [0.4, 0.3, 3, 2, 60] }, { id: 'defiance', v: [0.25, 0.15] }],
    passives: [
      ['魔人化', '敵ヒーローのダメージで HP が 40% を下回ると、3 秒間 ダメージ軽減 +30%、スキルのクールダウンを 2 秒 短縮する（CD 60 秒）。',
        'Demonize', 'When enemy hero damage drops you below 40% HP, gain 30% damage reduction for 3s and cut skill cooldowns by 2s (60s cooldown).'],
      ['反抗', '失った HP 1% につき 与えるダメージ +0.25%（最大 +15%）。',
        'Defiance', '+0.25% damage dealt per 1% HP lost (up to +15%).']] },
  { id: 'EQ313', cat: 'Defense', tier: 3, price: 1910, name: 'ブレイドアーマー', ne: 'Blade Armor', src: 'Blade Armor',
    tag: '通常攻撃反射', tage: 'Reflects attacks', from: ['EQ314', 'EQ323', 'EQ323'],
    stats: { armor: 80 }, unique: { crit_damage_reduction_pct: 20 },
    effects: [{ id: 'bladedArmor', v: [30, 0.02, 0.15, 1] }],
    passives: [['刃の鎧', 'クリティカルダメージ軽減 +20%（固有）。通常攻撃を受けると、受けたダメージ（軽減前）の（30 + 総物理防御の 2%）% の物理ダメージを攻撃者に返し、1 秒間 15% 減速させる。',
      'Bladed Armor', '+20% crit damage reduction (unique). When hit by a basic attack, deal (30 + 2% of total physical defense)% of the damage taken (before reduction) back to the attacker as physical damage and slow them by 15% for 1s.']] },
  // 素材・ポーション
  { id: 'EQ314', cat: 'Defense', tier: 2, price: 630, name: 'スチールレッグプレート', ne: 'Steel Legplates', src: 'Steel Legplates',
    from: ['EQ323'], stats: { armor: 35 } },
  { id: 'EQ315', cat: 'Defense', tier: 2, price: 730, name: 'ドレッドノートメイル', ne: 'Dreadnaught Armor', src: 'Dreadnaught Armor',
    from: ['EQ323', 'EQ323'], stats: { armor: 30 },
    effects: [{ id: 'deter', v: [0.04, 2, 3] }],
    passives: [['威嚇', 'スキルを受けると、攻撃者の物理ダメージを 2 秒間 4% 低下させる。最大 3 スタック。',
      'Deter', 'When hit by an enemy skill, the attacker\'s physical damage is reduced by 4% for 2s (up to 3 stacks).']] },
  { id: 'EQ316', cat: 'Defense', tier: 2, price: 780, name: 'アイスシールド', ne: 'Black Ice Shield', src: 'Black Ice Shield',
    from: ['EQ323', 'EQ322'], stats: { armor: 20, magic_resist: 20 },
    effects: [{ id: 'fortress', v: [4, 20, 500] }],
    passives: [['要塞の盾', '周り（5 マス）の敵ヒーロー 1 体につき 混合防御 +4（最大 +20）。',
      'Fortress Shield', '+4 hybrid defense per enemy hero within 5 units (up to +20).']] },
  { id: 'EQ317', cat: 'Defense', tier: 2, price: 1020, name: 'サイレンスローブ', ne: 'Silence Robe', src: 'Silence Robe',
    from: ['EQ324', 'EQ322'], stats: { hp: 540, magic_resist: 23 } },
  { id: 'EQ318', cat: 'Defense', tier: 2, price: 800, name: 'メルトエッセンス', ne: 'Molten Essence', src: 'Molten Essence',
    from: ['EQ324'], stats: { hp: 540 },
    effects: [{ id: 'burningSoul', v: [0.006, 1.25, 0.15, 350] }],
    passives: [['燃える魂', '周りの敵に 毎秒 最大 HP の 0.6% の魔法ダメージを与える。ミニオン・モンスターには +125%（+15%×レベル）。',
      'Burning Soul', 'Deal magic damage equal to 0.6% of your max HP per second to nearby enemies; +125% (+15% × level) against minions and monsters.']] },
  { id: 'EQ319', cat: 'Defense', tier: 2, price: 700, name: 'アレスベルト', ne: 'Ares Belt', src: 'Ares Belt',
    from: ['EQ324'], stats: { hp: 600 } },
  { id: 'EQ320', cat: 'Defense', tier: 1, price: 450, name: 'ブレイバーリング', ne: 'Hero\'s Ring', src: 'Hero\'s Ring',
    stats: { hp: 150, cooldown_reduction_pct: 5 } },
  { id: 'EQ321', cat: 'Defense', tier: 1, price: 140, name: 'ヒーリングネックレス', ne: 'Healing Necklace', src: 'Healing Necklace',
    stats: { hp_regen: 4 } },
  { id: 'EQ322', cat: 'Defense', tier: 1, price: 220, name: 'マジカルクローク', ne: 'Magic Resist Cloak', src: 'Magic Resist Cloak',
    stats: { magic_resist: 14 } },
  { id: 'EQ323', cat: 'Defense', tier: 1, price: 220, name: 'レザーメイル', ne: 'Leather Jerkin', src: 'Leather Jerkin',
    stats: { armor: 14 } },
  { id: 'EQ324', cat: 'Defense', tier: 1, price: 300, name: 'バイタリティクリスタル', ne: 'Vitality Crystal', src: 'Vitality Crystal',
    stats: { hp: 230 } },
  { id: 'EQ325', cat: 'Defense', tier: 1, price: 1500, name: 'ロックポーション', ne: 'Rock Potion', src: 'Rock Potion',
    consumable: 120, stats: { hp: 500, damage_reduction_pct: 5 },
    passives: [['堅牢', '買うとすぐに使われ、120 秒間 最大 HP +500、ダメージ軽減 +5%。所持枠を使わない。ポーションの効果は 1 つだけ。',
      'Increase Power', 'Used on purchase: +500 max HP and +5% damage reduction for 120s. Takes no slot; only one potion effect at a time.']] },

  // ───────────────────────────── 移動（靴は 1 足まで。Tier 2 の靴にジャングル・ロームの祝福を付けられる） ─────────────────────────────
  { id: 'EQ401', cat: 'Movement', tier: 2, price: 720, name: 'デモンブーツ', ne: 'Demon Shoes', src: 'Demon Shoes',
    tag: 'MP高速回復', tage: 'Mana regen', from: ['EQ408', 'EQ222', 'EQ222'],
    stats: { move_speed: 40, resource_regen: 10 },
    effects: [{ id: 'mysticism', v: [0.04] }],
    passives: [['神髄', '敵ミニオンをキルまたはアシストすると、最大 MP の 4% を回復する。',
      'Mysticism', 'Killing or assisting on an enemy minion restores 4% of max mana.']] },
  { id: 'EQ402', cat: 'Movement', tier: 2, price: 720, name: 'ラピッドブーツ', ne: 'Rapid Boots', src: 'Rapid Boots',
    tag: '高移動速度', tage: 'High move speed', from: ['EQ408', 'EQ321', 'EQ321'],
    stats: { move_speed: 55, slow_reduction_pct: 35, hp_regen: 12 } },
  { id: 'EQ403', cat: 'Movement', tier: 2, price: 720, name: 'スイフトブーツ', ne: 'Swift Boots', src: 'Swift Boots',
    tag: '攻撃速度', tage: 'Attack speed', from: ['EQ408', 'EQ132'],
    stats: { move_speed: 40, attack_speed_pct: 15 } },
  { id: 'EQ404', cat: 'Movement', tier: 2, price: 720, name: 'アーケインブーツ', ne: 'Arcane Boots', src: 'Arcane Boots',
    tag: '魔法貫通', tage: 'Magic penetration', from: ['EQ408', 'EQ224'],
    stats: { move_speed: 40, ability_power: 15, magic_pen_flat: 10 } },
  { id: 'EQ405', cat: 'Movement', tier: 2, price: 720, name: 'マジックブーツ', ne: 'Magic Shoes', src: 'Magic Shoes',
    tag: 'CD短縮', tage: 'Cooldown', from: ['EQ408', 'EQ320'],
    stats: { move_speed: 40, cooldown_reduction_pct: 10, hp: 150 } },
  { id: 'EQ406', cat: 'Movement', tier: 2, price: 720, name: 'タフブーツ', ne: 'Tough Boots', src: 'Tough Boots',
    tag: 'コントロール時間短縮', tage: 'CC reduction', from: ['EQ408', 'EQ322'],
    stats: { move_speed: 40, magic_resist: 18, cc_reduction_pct: 25 },
    passives: [['不屈', '受ける行動阻害と減速の効果時間 −25%。', 'Fortitude', 'Crowd control and slows on you last 25% shorter.']] },
  { id: 'EQ407', cat: 'Movement', tier: 2, price: 720, name: 'ウォリアーブーツ', ne: 'Warrior Boots', src: 'Warrior Boots',
    tag: '物理防御加算', tage: 'Physical defense', from: ['EQ408', 'EQ323'],
    stats: { move_speed: 40, armor: 18 },
    effects: [{ id: 'valor', v: [4, 3, 5] }],
    passives: [['勇気', '物理ダメージを受けると 3 秒間 物理防御 +4（5 回まで、+20）。',
      'Valor', 'Taking physical damage grants +4 physical defense for 3s (up to 5 stacks, +20).']] },
  { id: 'EQ408', cat: 'Movement', tier: 1, price: 250, name: 'スピードブーツ', ne: 'Boots', src: 'Boots',
    stats: { move_speed: 20 } },
];
